namespace Resources.Code
{
    public enum UICommandType
    {
        ShowException,
        AuthoriseActivate,
        AuthoriseDeactivate,
        SendQuery,
        MakeAdmin,
        MakeSeller,
        RefreshAccountInfo,
        ActivateShop,
        SendGoodsRequest,
        ShowGoodList,
        SendAccountRequest,
        ShowAccountList,
        ContinueAccountAdding,
        SendGamesRequest,
        ShowGamesList,
        ContinueGamesAdding,
        SendPaymentMethodsRequest,
        ShowPaymentMethodsList,
        ContinuePaymentMethodsAdding,
        SendSellersRequest,
        ShowSellersList,
        ContinueSellersAdding,
        SendAdminKeysRequest,
        ShowAdminKeysList,
        ContinueAdminKeysAdding,
        SendGoodsAPRequest,
        ShowGoodListAP
    }
}