namespace Resources.Code
{
    public enum UICommandType
    {
        ShowException,
        AuthoriseActivate,
        AuthoriseDeactivate,
        SendQuery,
        MakeAdmin,
        RefreshAccountInfo,
        ActivateShop,
        SendGoodsRequest,
        ShowGoodList,
        SendAccountRequest,
        ShowAccountList,
        ContinueAccountAdding,
        SendDiseasesRequest,
        ShowDiseasesList,
        ContinueDiseasesAdding,
        SendMedicineRequest,
        ShowMedicineList,
        ContinueMedicinesAdding,
        SendPlantsRequest,
        ShowPlantsList,
        ContinuePlantsAdding,
        SendAdminKeysRequest,
        ShowAdminKeysList,
        ContinueAdminKeysAdding,
        SendGoodsAPRequest,
        ShowGoodListAP,
        SendGoodsEditRequest,
        ShowGoodListEdit,
        ContinuePlantsDiseasesAdding
    }
}